<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-04-25 13:15:04
 * @@Modify Date: 2015-06-05 11:20:40
 * @@Function:
 */
?>
<?php //echo $this->getChildHtml('amenu') ?>
<?php echo $this->getChildHtml('vmenu') ?>

