<?php

/**

 * Magiccart 

 * @category 	Magiccart 

 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 

 * @license 	http://www.magiccart.net/license-agreement.html

 * @Author: DOng NGuyen<nguyen@dvn.com>

 * @@Create Date: 2014-05-08 22:57:12

 * @@Modify Date: 2014-12-18 19:24:50

 * @@Function:

 */

 ?>

<?php if(!$this->getGeneralCfg('enabled')) return; ?>

<?php $selector = $this->generateRandomString(); //md5(rand()); //rand(0,666666); ?>



<div class= "<?php echo $selector?> magicproduct">

<?php

$tabs = $this->getTabs();

$ajax = json_encode($this->getProductCfg());

if(count($tabs)): ?>

    <div class="block-title-tabs">

	<ul class="magictabs" data-ajax ='<?php echo $ajax ?>'>

	<?php $active = $this->getTabActive();

		$limit = $this->getNumProduct();

		foreach ($tabs as $type => $name):

			$status = ($type == $active) ? 'active loaded' : '';

			echo '<li class="item '.$status.'" data-type ="'.$type.'"><h3 class ="title"><span >'.$this->__($name).'</span></h3></li>';

		endforeach;

	?>

	</ul>

    </div>

<?php endif ?>

	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/ajax')?>">

		<img src="<?php echo $this->getSkinUrl('magiccart/plugin/images/loading.gif')?>" alt="<?php echo $this->__('Loading...');?>"/>

	</div>

	<?php 

		$margin  = (int) $this->getData('marginColumn');

		$slide   = json_encode($this->setFlexiselArray());

		$options = json_encode($this->getItemsDevice());

	?>

	<div class="content-products" data-margin="<?php echo $margin ?>" data-slider='<?php echo $slide ?>' data-options='<?php echo $options; ?>'>

		<?php echo $this->getContentActive('magiccart/magicproduct/product/grid2.phtml');?>

	</div>

	<!-- MAP -->

	<?php echo $this->getChildHtml('product.tooltip');?>

	<!-- MAP -->

</div>



<script type="text/javascript">

jQuery(document).ready(function () {

	jQuery(".<?php echo $selector?>").magicproduct({

		selector : ".<?php echo $selector?>", /* Selector product grid */

	});

});

</script>



