<?php if(!$this->config['enabled']) return;?>
<?php $title = isset($this->config['title']) ? $this->config['title'] : ''; ?>
<?php $selector = $this->generateRandomString(); //md5(rand()); //rand(0,666666); ?>
<?php $brands = $this->getBrand(); if(!count($brands)) return;?>
<div id="<?php echo $selector ?>" class="block-title-tabs">
    <?php echo $title ? '<h3 class="title"><span>'.$title.'</span></h3>' : '' ?>
    <ul class="magicbrand">
    <?php 
    $i = 0;
    $rows = 2;
    $size = count($brands);
    foreach ($brands as $brand) :?>
    <?php if($i % $rows == 0): ?> 
    	<li>
    <?php endif ?>
        <img class="brand" src="<?php echo $this->getImage($brand)?>" alt="<?php echo $this->__($brand->getTitle()) ?>" title="<?php echo $this->__($brand->getTitle()) ?>" />
    <?php $i++; if($i % $rows == 0 || $i== $size ): ?>
    	</li>
    <?php endif ?>
    <?php endforeach ?>
    </ul>
</div>

<script type="text/javascript">
    jQuery( document ).ready(function($) {
        (function(selector){
            var $content = $(selector);
            var $slider  = $('.magicbrand', $content);
            $slider.flexisel({
                // margin: 15,
                moveSlide: 1,
                <?php echo $this->setFlexisel() ?>
            });
        })("#<?php echo $selector ?>");
    });
</script>



