<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-06-07 12:27:23
 * @@Modify Date: 2014-09-29 19:57:54
 * @@Function:
 */ 
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<?php $_items = $this->getRecentItems(); ?>
<div class="mini-maincart">
	<div class="cartSummary">
		<span class="icon-cart fa fa-shopping-cart"><?php //echo $this->__('Cart:') ?></span>
		<span class="item"><?php //echo ($_cartQty >1) ? $_cartQty .' ' .$this->__('item(s)') : $_cartQty .' '.$this->__('item'); ?></span>
		<span><?php //echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></span>		
	</div>
	<div class="mini-contentCarts">
		<?php if(count($_items)): ?>
        <div class="block-content">
            <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
            <ol id="cart-sidebar" class="mini-products-list clearfix">
                <?php foreach($_items as $_item): ?>
                    <span><?php echo $this->getItemHtml($_item) ?></span>
                <?php endforeach; ?>
            </ol>
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>
            <div class="actions">
                <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="view-cart">
                    <?php echo $this->__('View cart') ?>
                </a>
                <a href="<?php echo $this->getCheckoutUrl() ?>"><?php echo $this->__('Checkout') ?></a>
                <?php  echo $this->getChildHtml('extra_actions')  ?>
            </div>
            <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
        </div>

		<?php else: ?>
		<div class="block-content">
			<p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
		</div>
		<?php endif ?>	
	</div>
</div>

